/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/_student/route'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedStudentContestsRouteImport } from './routes/_authenticated/_student/contests'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/_student/dashboard'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/_student/profile'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated/_admin/admin.audit'
import { Route as AuthenticatedAdminAdminContestsRouteImport } from './routes/_authenticated/_admin/admin.contests'
import { Route as AuthenticatedAdminAdminQuestionsRouteImport } from './routes/_authenticated/_admin/admin.questions'
import { Route as AuthenticatedAdminAdminStudentsRouteImport } from './routes/_authenticated/_admin/admin.students'
import { Route as AuthenticatedStudentContestIdArenaRouteImport } from './routes/_authenticated/_student/contest.$id.arena'
import { Route as AuthenticatedStudentContestIdLobbyRouteImport } from './routes/_authenticated/_student/contest.$id.lobby'
import { Route as AuthenticatedStudentContestIdResultRouteImport } from './routes/_authenticated/_student/contest.$id.result'
import { Route as AuthenticatedStudentContestIdReviewRouteImport } from './routes/_authenticated/_student/contest.$id.review'
import { Route as AuthenticatedAdminAdminContestsIdMonitorRouteImport } from './routes/_authenticated/_admin/admin.contests.$id.monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentContestsRoute =
  AuthenticatedStudentContestsRouteImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminContestsRoute =
  AuthenticatedAdminAdminContestsRouteImport.update({
    id: '/admin/contests',
    path: '/admin/contests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminQuestionsRoute =
  AuthenticatedAdminAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminStudentsRoute =
  AuthenticatedAdminAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStudentContestIdArenaRoute =
  AuthenticatedStudentContestIdArenaRouteImport.update({
    id: '/contest/$id/arena',
    path: '/contest/$id/arena',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentContestIdLobbyRoute =
  AuthenticatedStudentContestIdLobbyRouteImport.update({
    id: '/contest/$id/lobby',
    path: '/contest/$id/lobby',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentContestIdResultRoute =
  AuthenticatedStudentContestIdResultRouteImport.update({
    id: '/contest/$id/result',
    path: '/contest/$id/result',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentContestIdReviewRoute =
  AuthenticatedStudentContestIdReviewRouteImport.update({
    id: '/contest/$id/review',
    path: '/contest/$id/review',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminAdminContestsIdMonitorRoute =
  AuthenticatedAdminAdminContestsIdMonitorRouteImport.update({
    id: '/$id/monitor',
    path: '/$id/monitor',
    getParentRoute: () => AuthenticatedAdminAdminContestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/contests': typeof AuthenticatedStudentContestsRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/contests': typeof AuthenticatedAdminAdminContestsRouteWithChildren
  '/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/contest/$id/arena': typeof AuthenticatedStudentContestIdArenaRoute
  '/contest/$id/lobby': typeof AuthenticatedStudentContestIdLobbyRoute
  '/contest/$id/result': typeof AuthenticatedStudentContestIdResultRoute
  '/contest/$id/review': typeof AuthenticatedStudentContestIdReviewRoute
  '/admin/contests/$id/monitor': typeof AuthenticatedAdminAdminContestsIdMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/contests': typeof AuthenticatedStudentContestsRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/contests': typeof AuthenticatedAdminAdminContestsRouteWithChildren
  '/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/contest/$id/arena': typeof AuthenticatedStudentContestIdArenaRoute
  '/contest/$id/lobby': typeof AuthenticatedStudentContestIdLobbyRoute
  '/contest/$id/result': typeof AuthenticatedStudentContestIdResultRoute
  '/contest/$id/review': typeof AuthenticatedStudentContestIdReviewRoute
  '/admin/contests/$id/monitor': typeof AuthenticatedAdminAdminContestsIdMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/_student/contests': typeof AuthenticatedStudentContestsRoute
  '/_authenticated/_student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/_student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/contests': typeof AuthenticatedAdminAdminContestsRouteWithChildren
  '/_authenticated/_admin/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/_authenticated/_admin/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_student/contest/$id/arena': typeof AuthenticatedStudentContestIdArenaRoute
  '/_authenticated/_student/contest/$id/lobby': typeof AuthenticatedStudentContestIdLobbyRoute
  '/_authenticated/_student/contest/$id/result': typeof AuthenticatedStudentContestIdResultRoute
  '/_authenticated/_student/contest/$id/review': typeof AuthenticatedStudentContestIdReviewRoute
  '/_authenticated/_admin/admin/contests/$id/monitor': typeof AuthenticatedAdminAdminContestsIdMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/login'
    | '/rules'
    | '/change-password'
    | '/leaderboard'
    | '/contests'
    | '/dashboard'
    | '/profile'
    | '/admin/audit'
    | '/admin/contests'
    | '/admin/questions'
    | '/admin/students'
    | '/admin/'
    | '/contest/$id/arena'
    | '/contest/$id/lobby'
    | '/contest/$id/result'
    | '/contest/$id/review'
    | '/admin/contests/$id/monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/login'
    | '/rules'
    | '/change-password'
    | '/leaderboard'
    | '/contests'
    | '/dashboard'
    | '/profile'
    | '/admin/audit'
    | '/admin/contests'
    | '/admin/questions'
    | '/admin/students'
    | '/admin'
    | '/contest/$id/arena'
    | '/contest/$id/lobby'
    | '/contest/$id/result'
    | '/contest/$id/review'
    | '/admin/contests/$id/monitor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/features'
    | '/login'
    | '/rules'
    | '/_authenticated/_admin'
    | '/_authenticated/_student'
    | '/_authenticated/change-password'
    | '/_authenticated/leaderboard'
    | '/_authenticated/_student/contests'
    | '/_authenticated/_student/dashboard'
    | '/_authenticated/_student/profile'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/contests'
    | '/_authenticated/_admin/admin/questions'
    | '/_authenticated/_admin/admin/students'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_student/contest/$id/arena'
    | '/_authenticated/_student/contest/$id/lobby'
    | '/_authenticated/_student/contest/$id/result'
    | '/_authenticated/_student/contest/$id/review'
    | '/_authenticated/_admin/admin/contests/$id/monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student/contests': {
      id: '/_authenticated/_student/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof AuthenticatedStudentContestsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/dashboard': {
      id: '/_authenticated/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/profile': {
      id: '/_authenticated/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/contests': {
      id: '/_authenticated/_admin/admin/contests'
      path: '/admin/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AuthenticatedAdminAdminContestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/questions': {
      id: '/_authenticated/_admin/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/students': {
      id: '/_authenticated/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_student/contest/$id/arena': {
      id: '/_authenticated/_student/contest/$id/arena'
      path: '/contest/$id/arena'
      fullPath: '/contest/$id/arena'
      preLoaderRoute: typeof AuthenticatedStudentContestIdArenaRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/contest/$id/lobby': {
      id: '/_authenticated/_student/contest/$id/lobby'
      path: '/contest/$id/lobby'
      fullPath: '/contest/$id/lobby'
      preLoaderRoute: typeof AuthenticatedStudentContestIdLobbyRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/contest/$id/result': {
      id: '/_authenticated/_student/contest/$id/result'
      path: '/contest/$id/result'
      fullPath: '/contest/$id/result'
      preLoaderRoute: typeof AuthenticatedStudentContestIdResultRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/contest/$id/review': {
      id: '/_authenticated/_student/contest/$id/review'
      path: '/contest/$id/review'
      fullPath: '/contest/$id/review'
      preLoaderRoute: typeof AuthenticatedStudentContestIdReviewRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_admin/admin/contests/$id/monitor': {
      id: '/_authenticated/_admin/admin/contests/$id/monitor'
      path: '/$id/monitor'
      fullPath: '/admin/contests/$id/monitor'
      preLoaderRoute: typeof AuthenticatedAdminAdminContestsIdMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminAdminContestsRoute
    }
  }
}

interface AuthenticatedAdminAdminContestsRouteChildren {
  AuthenticatedAdminAdminContestsIdMonitorRoute: typeof AuthenticatedAdminAdminContestsIdMonitorRoute
}

const AuthenticatedAdminAdminContestsRouteChildren: AuthenticatedAdminAdminContestsRouteChildren =
  {
    AuthenticatedAdminAdminContestsIdMonitorRoute:
      AuthenticatedAdminAdminContestsIdMonitorRoute,
  }

const AuthenticatedAdminAdminContestsRouteWithChildren =
  AuthenticatedAdminAdminContestsRoute._addFileChildren(
    AuthenticatedAdminAdminContestsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminContestsRoute: typeof AuthenticatedAdminAdminContestsRouteWithChildren
  AuthenticatedAdminAdminQuestionsRoute: typeof AuthenticatedAdminAdminQuestionsRoute
  AuthenticatedAdminAdminStudentsRoute: typeof AuthenticatedAdminAdminStudentsRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
    AuthenticatedAdminAdminContestsRoute:
      AuthenticatedAdminAdminContestsRouteWithChildren,
    AuthenticatedAdminAdminQuestionsRoute:
      AuthenticatedAdminAdminQuestionsRoute,
    AuthenticatedAdminAdminStudentsRoute: AuthenticatedAdminAdminStudentsRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentContestsRoute: typeof AuthenticatedStudentContestsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentContestIdArenaRoute: typeof AuthenticatedStudentContestIdArenaRoute
  AuthenticatedStudentContestIdLobbyRoute: typeof AuthenticatedStudentContestIdLobbyRoute
  AuthenticatedStudentContestIdResultRoute: typeof AuthenticatedStudentContestIdResultRoute
  AuthenticatedStudentContestIdReviewRoute: typeof AuthenticatedStudentContestIdReviewRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentContestsRoute: AuthenticatedStudentContestsRoute,
    AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
    AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
    AuthenticatedStudentContestIdArenaRoute:
      AuthenticatedStudentContestIdArenaRoute,
    AuthenticatedStudentContestIdLobbyRoute:
      AuthenticatedStudentContestIdLobbyRoute,
    AuthenticatedStudentContestIdResultRoute:
      AuthenticatedStudentContestIdResultRoute,
    AuthenticatedStudentContestIdReviewRoute:
      AuthenticatedStudentContestIdReviewRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
